name: ChatSpace Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: chatspace.bond
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          timeout: 30s
          command_timeout: 240m
          script: |
            set -e
            cd /chatspace/chatspace-fe-simple
            git pull
            npm install
            npm run build
            docker restart nginx
